execute_process(COMMAND "${UG_BINARY}" --version RESULT_VARIABLE result OUTPUT_VARIABLE version)
if(NOT result EQUAL 0 OR NOT version MATCHES "0.1.0-beta.1")
  message(FATAL_ERROR "version command failed")
endif()
execute_process(COMMAND "${UG_BINARY}" --help RESULT_VARIABLE result OUTPUT_VARIABLE help)
if(NOT result EQUAL 0 OR NOT help MATCHES "list-checks")
  message(FATAL_ERROR "help command failed")
endif()
execute_process(COMMAND "${UG_BINARY}" list-checks RESULT_VARIABLE result OUTPUT_VARIABLE checks)
if(NOT result EQUAL 0 OR NOT checks MATCHES "UG-RBT-001")
  message(FATAL_ERROR "list-checks command failed")
endif()
execute_process(COMMAND "${UG_BINARY}" explain UG-APT-004 RESULT_VARIABLE result OUTPUT_VARIABLE explanation)
if(NOT result EQUAL 0 OR NOT explanation MATCHES "Third-party")
  message(FATAL_ERROR "explain command failed")
endif()
set(report "${CMAKE_CURRENT_BINARY_DIR}/cli-report.json")
execute_process(COMMAND "${UG_BINARY}" export --format json --output "${report}" --force RESULT_VARIABLE result)
if(result GREATER 3 OR NOT EXISTS "${report}")
  message(FATAL_ERROR "JSON export failed with ${result}")
endif()
file(READ "${report}" json)
string(JSON schema ERROR_VARIABLE json_error GET "${json}" schema_version)
if(json_error OR NOT schema STREQUAL "1.0")
  message(FATAL_ERROR "JSON report is invalid: ${json_error}")
endif()
